lansguage: node_js
node_js: stable
branchs:
  only:
  - master
before_install:
  - npm install -g yarn --cache-min 999999999
  - npm install -g codecov
install:
- yarn install
script:
- yarn run test
- codecov -t $uploadtoken
cache: yarn
